college_app/urls.py
from django.urls import path
from . import views
app_name='college_app'
urlpatterns = [
    path('', views.collegestore, name='collegestore'),
    path('reg',views.reg,name='reg')
]

college_store_project/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('college_app/', include('college_app.urls')),
    path('credentials_app/', include('credentials_app.urls')),
]
if settings.DEBUG:
 urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
 urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credentials_app/urls.py
from django.urls import path
from . import views
app_name='credentials_app'
urlpatterns = [
    path('register', views.register, name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout')

]

college_app/models.py
from django.db import models



# Create your models here.

class Department(models.Model):
    dept_id=models.CharField(max_length=259,blank=True)
    dept_name=models.CharField(max_length=259)
    class Meta:
        db_table='Department'
        ordering=['dept_id']
    def __str__(self):
        return '{}'.format(self.dept_name)

class Purpose(models.Model):
    purpose_id=models.CharField(max_length=259,blank=True)
    purpose_name=models.CharField(max_length=259)
    class Meta:
        db_table='Purpose'
        ordering=['purpose_id']
    def __str__(self):
        return '{}'.format(self.purpose_name)

class Course(models.Model):
    course_id=models.CharField(max_length=259,blank=True)
    dept_id= models.ForeignKey(Department, on_delete=models.CASCADE)
    course_name=models.CharField(max_length=259)
    class Meta:
        db_table='Course'
        ordering=['course_id']
    def __str__(self):
        return '{}'.format(self.course_name)

class Register(models.Model):
    name = models.CharField(max_length=259, blank=True)
    dob = models.DateField()
    age = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    mail_id = models.EmailField()
    address = models.TextField(blank=True)
    course= models.ForeignKey(Course, on_delete=models.CASCADE)
    purpose=models.ForeignKey(Purpose, on_delete=models.CASCADE)
    material=models.TextField()
    dept_name=models.ForeignKey(Department, on_delete=models.CASCADE)
    class Meta:
        db_table = 'Register'

    def __str__(self):
        return '{}'.format(self.name)

credentials_app/models.py
from django.db import models

# Create your models here.

college_app/views.py
from django.contrib import messages

from django.shortcuts import render, redirect
from .models import Register,Department,Course
def collegestore(request):
    dept=Department.objects.all()
    return render(request,'index.html',{'dept':dept})
def reg(request):


    # if request.method == 'POST':
    #     name = request.POST.get('name')
    #     dob = request.POST.get('dob')
    #     age = request.POST.get('age')
    #     phone = request.POST.get('phone')
    #     email = request.POST.get('email')
    #     course = request.POST.get('course')
    #     purpose = request.POST.get('purpose')
    #     material = request.POST.get('material')
    #     address = request.POST.get('address')
    #     dept_name=request.POST.get('dept_name')
    #     register=Register.objects.create_user(name=name,dob=dob,age=age,phone=phone,e_mail=email,course=course,purpose=purpose,material=material,address=address,dept_name=dept_name)
    #     register.save();
    #       messages.success(request, 'Order confirmed')
    #       return redirect('/')
            return render(request, 'reg.html')

credentials_app/views.py
from django.shortcuts import render
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def login(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)


            return redirect('college_app:reg')
        else:

            return redirect('credentials_app:login')
    return render(request,'login.html')
def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        confpassword = request.POST['confpassword']
        if(password==confpassword):
            if User.objects.filter(username=username).exists():
                messages.info(request, "* username already exist *")
                return redirect('credentials_app:register')

            else:

                user = User.objects.create_user(username=username, password=password)
                user.save();

                return redirect('credentials_app:login')

        else:
            messages.info(request, "*password not matching*")
            return redirect('credentials_app:register')


    return render(request, 'register.html')
def logout(request):
    auth.logout(request)
    return redirect('/')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href=" {% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Audiowide">
    <script src="https://kit.fontawesome.com/45ecc44b89.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container" >
    {% include 'header.html' %}
     {% include 'navbar.html' %}

     {% block content %}
     {% endblock %}
    </div>
     {% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">&copy; shrishti school All rights reserved</p>
</div>

templates/header.html
{% load static %}
<header>
<center>
<a href=""></a><img src="{% static 'img/newlogo.png' %}" alt="logimage" width="100" height="100">
   </center>
</header>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
Welcome....!!!!!

{% endblock %}
{% block content %}

<div>
 <img class="my_image my_image_padding" src="{% static 'img/newbanner.png' %}" alt="" width=1280>
</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
Welcome....!!!!!

{% endblock %}
{% block content %}

<div>
 <img class="my_image my_image_padding" src="{% static 'img/newbanner.png' %}" alt="" width=1280>
</div>

{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
	<style>
 body{
	margin: 0;
	padding: 0;
	display: flex;
	justify-content: center;
	align-items: center;
	min-height: 100vh;
	font-family: 'Jost', sans-serif;
	background: linear-gradient(to bottom, #0f0c29, #302b63, #24243e);
}
.main{
	width: 350px;
	height: 500px;
	background: red;
	overflow: hidden;
	background: url("https://doc-08-2c-docs.googleusercontent.com/docs/securesc/68c90smiglihng9534mvqmq1946dmis5/fo0picsp1nhiucmc0l25s29respgpr4j/1631524275000/03522360960922298374/03522360960922298374/1Sx0jhdpEpnNIydS4rnN4kHSJtU1EyWka?e=view&authuser=0&nonce=gcrocepgbb17m&user=03522360960922298374&hash=tfhgbs86ka6divo3llbvp93mg4csvb38") no-repeat center/ cover;
	border-radius: 10px;
	box-shadow: 5px 20px 50px #000;
}
#chk{
	display: none;
}
.signup{
	position: relative;
	width:100%;
	height: 100%;
}
label{
	color: #fff;
	font-size: 2.3em;
	justify-content: center;
	display: flex;
	margin: 60px;
	font-weight: bold;
	cursor: pointer;
	transition: .5s ease-in-out;
}
input{
	width: 60%;
	height: 20px;
	background: #e0dede;
	justify-content: center;
	display: flex;
	margin: 20px auto;
	padding: 10px;
	border: none;
	outline: none;
	border-radius: 5px;
}
button{
	width: 60%;
	height: 40px;
	margin: 10px auto;
	justify-content: center;
	display: block;
	color: #fff;
	background: #573b8a;
	font-size: 1em;
	font-weight: bold;
	margin-top: 20px;
	outline: none;
	border: none;
	border-radius: 5px;
	transition: .2s ease-in;
	cursor: pointer;
}
button:hover{
	background: #6d44b8;
}
.login{
	height: 460px;
	background: #eee;
	border-radius: 60% / 10%;
	transform: translateY(-180px);
	transition: .8s ease-in-out;
}
.login label{
	color: #573b8a;
	transform: scale(.6);
}

#chk:checked ~ .login{
	transform: translateY(-500px);
}
#chk:checked ~ .login label{
	transform: scale(1);
}
#chk:checked ~ .signup label{
	transform: scale(.6);
}
.link
{
color:white;
}

	</style>
</head>
<body>
<form class='login-form' action="login" method="post">
	 {% csrf_token %}
	<div class="main">
		<input type="checkbox" id="chk" aria-hidden="true">

			<div class="signup">
				<form>
					<label for="chk" aria-hidden="true">LOGIN</label>
					<input type="text" name="username" placeholder="User name" required="">

					<input type="password" name="password" placeholder="Password" required="">

					<button>login</button>
					 <a class="link" href="{% url 'credentials_app:register' %}">Register Here.....</a>
				</form>

			</div>
		</div>
</form>
{% for msg in messages %}
  <h2>{{msg}}</h2>
  {% endfor %}
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'credentials_app:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'credentials_app:register' %}">Register</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Department
          </a>
        <ul class="dropdown-menu">

              {% for i in dept %}

            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/{{i.dept_name}}">{{i.dept_name}}</a></li>
              {% endfor %}


         </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/reg.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min./js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<style>
   body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}
/* Button used to open the contact form - fixed at the bottom of the page */
.mycontainer{
  background-color: #555;
  color: white;
  padding: 16px 20px;
  border: none;
  cursor: pointer;
  opacity: 0.8;
  position: fixed;
  bottom: 30px;
  right: 40px;
  width: 350px;
}

/* The popup form - hidden by default */
.form-popup {
  display: none;
  position: fixed;
  center: 0;
  background_color:blue;
  border: 3px solid #f1f1f1;
  z-index: 9;
}

/* Add styles to the form container */
.form-container {
  max-width: 2000px;
  padding: 10px;
  background-color: blue;
}

/* Full-width input fields */
.form-container input[type=text], .form-container input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  border: none;
  background: #f1f1f1;
}

/* When the inputs get focus, do something */
.form-container input[type=text]:focus, .form-container input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Set a style for the submit/login button */
 .btn {
  background-color: #04AA6D;
  color: red;
  padding: 16px 20px;

  cursor: pointer;
  width: 100%;
  margin-bottom:10px;
  opacity: 0.8;
}

/* Add a red background color to the cancel button */
.btn_cancel {
  color: red;
  padding: 16px 20px;
  border: none;
  cursor: pointer;
  opacity: 0.8;
  position: fixed;
  bottom: 30px;
  left: 40px;
  width: 280px;
}

/* Add some hover effects to buttons */
.form-container .btn:hover, .open-button:hover {
  opacity: 1;
}
</style>

</head>
<body>
<div class="mycontainer">
<div class="title">Click open form to place order Registration</div>
<button class="open-button" onclick="openForm()">Open Form</button>
<ul>
    {% if user.is_authenticated %}
    <li>hello {{user.username}} <a href="{% url 'credentials_app:logout' %}">Logout</a></li>
    {% endif %}
          </ul>
 <br><button type="button" class="btn_cancel" onclick="closeForm()">Close</button>
</div>
<div class="container">

    <div class="content">
      <div class="form-popup" id="myForm">

      <form class="form" id="form1" action="reg" method="POSt">
        {% csrf_token %}
       <div class="user-details">
        <div class="input-box"><br>
          <label>Name</label>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <input type="text" name="name" placeholder="Enter name" required />
        </div>
        <div class="input-box"><br>
          <label> Date of birth</label>
          <input type="date" name="dob" placeholder="Enter date of birth" required />
       </div>

       <div class="input-box"><br>
          <label>age</label>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <input type="text" name="age" placeholder="Enter age" required />
       </div>
           <div class="input-box"><br>
          <label>phone</label>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <input type="text" name="phone" placeholder="Enter phone number" required />
        </div>
        <div class="input-box"><br>
          <label>Email </label>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <input type="email" name="email" placeholder="Enter email address" required />
        </div>
        <div class="input-box"><br>
          <label>Purpose</label>&nbsp&nbsp&nbsp&nbsp&nbsp
         <select name="purpose">
             <option>select purpose</option>
             {% for i in register %}
                   <option value="{{ i.purpose_id}}">{{i.purpose_name}}</option>

             {% endfor %}
         </select>
          </div>

<div class="input-box"><br>materials :
 <label>Notebook</label>
  <input type="checkbox">&nbsp&nbsp
 <label>Exampaper</label>
  <input type="checkbox">&nbsp&nbsp
    <label>Pen</label>
  <input type="checkbox">
        </div>
        <div class="input-box"><br>
          <label>Address</label>&nbsp&nbsp&nbsp&nbsp&nbsp
          <input type="text" name="address" placeholder="Enter address" required />
        </div>
          <div class="input-box"><br>
          <label>Department</label>&nbsp&nbsp&nbsp&nbsp&nbsp
         <select name="select1" id="select1">
             <option value="0">select department</option>
             {% for i in links %}
                   <option value="{{i.dept_id}}">{{i.dept_name}}</option>
             {% endfor %}
         </select>
          </div>

           <div class="input-box"><br>
          <label>Course</label>&nbsp&nbsp&nbsp&nbsp&nbsp
         <select name="select2" id="select2">
             <option value="0"></option>
             {% for j in cou %}
                    <option value="{{j.course_id}}">{{j.course_name}}</option>
             {% endfor %}
         </select>
          </div>
          </div>
  </form>
          <button onclick="myfun()">submit</button>
      </div>
</div>
</div>
<script>
function myfun()
{
    alert('your order confirmed');
    window.location.replace("/");
}
</script>
        <script>
function openForm() {

  document.getElementById("myForm").style.display = "block";
}

function closeForm() {
  document.getElementById("myForm").style.display = "none";
}
</script>
     <script>
$(document).ready(function(){

 var department = $("#select1");
 var course = $("#select2");
 var $options = course.find('option');
 department.on('change',function(){
    course.html($options.filter('[value="'+ this.value  +'"]'));
 }).trigger('change');

});
</script>
 </body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
	<style>
 body{
	margin: 0;
	padding: 0;
	display: flex;
	justify-content: center;
	align-items: center;
	min-height: 100vh;
	font-family: 'Jost', sans-serif;
	background: linear-gradient(to bottom, #0f0c29, #302b63, #24243e);
}
.main{
	width: 350px;
	height: 500px;
	background: red;
	overflow: hidden;
	background: url("https://doc-08-2c-docs.googleusercontent.com/docs/securesc/68c90smiglihng9534mvqmq1946dmis5/fo0picsp1nhiucmc0l25s29respgpr4j/1631524275000/03522360960922298374/03522360960922298374/1Sx0jhdpEpnNIydS4rnN4kHSJtU1EyWka?e=view&authuser=0&nonce=gcrocepgbb17m&user=03522360960922298374&hash=tfhgbs86ka6divo3llbvp93mg4csvb38") no-repeat center/ cover;
	border-radius: 10px;
	box-shadow: 5px 20px 50px #000;
}
#chk{
	display: none;
}
.signup{
	position: relative;
	width:100%;
	height: 100%;
}
label{
	color: #fff;
	font-size: 2.3em;
	justify-content: center;
	display: flex;
	margin: 60px;
	font-weight: bold;
	cursor: pointer;
	transition: .5s ease-in-out;
}
input{
	width: 60%;
	height: 20px;
	background: #e0dede;
	justify-content: center;
	display: flex;
	margin: 20px auto;
	padding: 10px;
	border: none;
	outline: none;
	border-radius: 5px;
}
button{
	width: 60%;
	height: 40px;
	margin: 10px auto;
	justify-content: center;
	display: block;
	color: #fff;
	background: #573b8a;
	font-size: 1em;
	font-weight: bold;
	margin-top: 20px;
	outline: none;
	border: none;
	border-radius: 5px;
	transition: .2s ease-in;
	cursor: pointer;
}
button:hover{
	background: #6d44b8;
}
.login{
	height: 460px;
	background: #eee;
	border-radius: 60% / 10%;
	transform: translateY(-180px);
	transition: .8s ease-in-out;
}
.login label{
	color: #573b8a;
	transform: scale(.6);
}

#chk:checked ~ .login{
	transform: translateY(-500px);
}
#chk:checked ~ .login label{
	transform: scale(1);
}
#chk:checked ~ .signup label{
	transform: scale(.6);
}

	</style>
</head>
<body>
<form class='login-form' action="register" method="post">
	 {% csrf_token %}
	<div class="main">
		<input type="checkbox" id="chk" aria-hidden="true">

			<div class="signup">
				<form>
					<label for="chk" aria-hidden="true">Register</label>
					<input type="text" name="username" placeholder="Username" required="">

					<input type="password" name="password" placeholder="Password" required="">
                    <input type="password" name="confpassword" placeholder="Confirm Password" required="">

					<button>submit</button>
				</form>

			</div>
		</div>


<!--	</div>-->
</form>
{% for msg in messages %}
  <h2>{{msg}}</h2>
  {% endfor %}
</body>
</html>